/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2014-12-12 14:44:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class showNews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/libraries.jspf", Long.valueOf(1418392546000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html ng-app=\"newsService\">\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>news</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<!-- Optional theme -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Latest compiled and minified JavaScript -->\n");
      out.write("    <script type=\"text/javascript\" src=\"/angularJS/angular.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"showNews.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"review.js\"></script>");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body ng-controller= \"newsController as newsCon\">\n");
      out.write("    \n");
      out.write("    <!--header bar-->\n");
      out.write("    <ol class=\"breadcrumb\">\n");
      out.write("        <li><a href=\"#\">News List</a></li>\n");
      out.write("        <li class=\"active\">Current News</li>\n");
      out.write("    </ol>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <!--news-->\n");
      out.write("    <div class=\"media\">\n");
      out.write("        <!--article-->\n");
      out.write("        <div class=\"media-body col-md-8\">\n");
      out.write("            <h1 class=\"media-heading text-center\">{{newsCon.articles[0].title}}</h1>\n");
      out.write("            <h3 class=\"col-md-6\"><small><em>{{newsCon.articles[0].date}}</em></small></h3>\n");
      out.write("            <h3 class=\"col-md-2 pull-right\"><small>{{newsCon.articles[0].author}}</small></h3>\n");
      out.write("            <p class=\"col-md-8\">{{newsCon.articles[0].article}}</p>\n");
      out.write("        </div>    \n");
      out.write("            \n");
      out.write("        <!--review-->\n");
      out.write("        <div class=\"col-md-8\">\n");
      out.write("            <h2 class=\"text-center\"> <small>Reviews</small> </h2>\n");
      out.write("            <blockquote ng-repeat=\"review in newsCon.articles[0].reviews\">\n");
      out.write("                {{review.body}}\n");
      out.write("                <br>\n");
      out.write("                <cite class=\"clearfix\"> <small> {{review.name}}</small></cite>\n");
      out.write("            </blockquote>\n");
      out.write("            \n");
      out.write("            <!--  Live Preview -->\n");
      out.write("            <form  ng-controller=\"ReviewController as reviewCon\" name=\"reviewForm\" novalidate method=\"POST\" action=\"/addReview_action.jsp\"  >\n");
      out.write("                <blockquote>\n");
      out.write("                    {{reviewCon.review.body}}\n");
      out.write("                    <br>\n");
      out.write("                    <cite class=\"clearfix\"> <small> {{reviewCon.review.name}}</small></cite>\n");
      out.write("                </blockquote>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- review form -->\n");
      out.write("\n");
      out.write("                <fieldset class=\"form-group\" >\n");
      out.write("                    <textarea type=\"text\" name=\"body\" ng-model=\"reviewCon.review.body\" class=\"form-control\" placeholder=\"review\" required ></textarea>\n");
      out.write("                </fieldset>\n");
      out.write("                <fieldset class=\"form-group\">\n");
      out.write("                    <input type=\"text\" name=\"name\" ng-model=\"reviewCon.review.name\" class=\"form-control\" placeholder=\"name\" required />\n");
      out.write("                </fieldset>\n");
      out.write("                <fieldset class=\"form-group\">\n");
      out.write("                    <input type=\"submit\" class=\"btn btn-primary pull-right\"/>\n");
      out.write("                </fieldset>\n");
      out.write("\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
